# Generated by Django 3.1.4 on 2021-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
