# Generated by Django 3.1.4 on 2021-12-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
