# Generated by Django 3.1.4 on 2021-12-14 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=64)),
                ('image', models.CharField(blank=True, max_length=10000, null=True)),
                ('category', models.CharField(choices=[('Vehicles', 'Vehicles'), ('Coins & Bullion', 'Coins & Bullion'), ('Art', 'Art'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Jewelry', 'Jewelry')], default='Vehicles', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('init_price', models.IntegerField(blank=True, null=True)),
                ('highest_bidding', models.IntegerField(default=0)),
                ('bid_increment', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_date')),
                ('bidder_counter', models.IntegerField(default=0)),
                ('favorite_counter', models.IntegerField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('is_expirated', models.BooleanField(default=False)),
                ('bidder', models.ManyToManyField(related_name='item_bidder', through='items.Bidders', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bidders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AddField(
            model_name='bidders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
