# Generated by Django 3.1.4 on 2021-12-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_expirated',
        ),
    ]
