# Generated by Django 3.1.4 on 2021-12-09 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_highest_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bidder_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='end_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end_data'),
        ),
        migrations.AddField(
            model_name='item',
            name='start_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start_data'),
        ),
    ]
