# Generated by Django 3.1.4 on 2021-12-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211209_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bidder',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
