# Generated by Django 3.1.4 on 2021-12-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20211211_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Vehicles', 'Vehicles'), ('Coins & Bullion', 'Coins & Bullion'), ('Art', 'Art'), ('Furniture', 'furniture'), ('Electronics', 'electronics'), ('Jewelry', 'jewelry')], default='Vehicles', max_length=100),
        ),
    ]
