# Generated by Django 3.1.4 on 2021-12-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20211211_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='is_expirated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
