# Generated by Django 3.1.4 on 2021-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20211211_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Vehicles', 'Vehicles'), ('Coins & Bullion', 'Coins & Bullion'), ('Art', 'Art'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Jewelry', 'Jewelry')], default='All', max_length=100),
        ),
    ]
