# Generated by Django 3.1.4 on 2021-12-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20211212_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='min_bid',
            field=models.IntegerField(default=0),
        ),
    ]
