# Generated by Django 3.1.4 on 2021-12-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20211212_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='min_bid',
        ),
    ]
