# Generated by Django 3.1.4 on 2021-12-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20211211_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
