# Generated by Django 3.1.4 on 2021-12-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20211212_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='min_bid',
            new_name='bid_increment',
        ),
        migrations.RemoveField(
            model_name='item',
            name='highest_bidder',
        ),
        migrations.AddField(
            model_name='item',
            name='highest_bidding',
            field=models.IntegerField(default=0),
        ),
    ]
