# Generated by Django 3.1.4 on 2021-12-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20211212_0959'),
        ('items', '0011_auto_20211212_1204'),
    ]

    operations = [
    ]
