# Generated by Django 3.1.4 on 2021-12-12 17:07

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20211212_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bidding',
            field=models.IntegerField(default=0),
        ),
    ]
