# Generated by Django 3.1.4 on 2021-12-12 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_merge_20211212_1620'),
        ('items', '0018_auto_20211212_1709'),
    ]

    operations = [
    ]
