# Generated by Django 3.1.4 on 2021-12-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_merge_20211212_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
