# Generated by Django 3.1.4 on 2021-12-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_auto_20211213_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bidding',
            field=models.IntegerField(default=models.IntegerField(blank=True, null=True)),
        ),
    ]
