# Generated by Django 3.1.4 on 2021-12-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_auto_20211213_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_bidding',
            field=models.IntegerField(default=0),
        ),
    ]
